a1.sources=source1
a1.channels=channel1
a1.sinks=sink1

#######################
# SOURCE (Kafka)
#######################
a1.sources.source1.type=org.apache.flume.source.kafka.KafkaSource
a1.sources.source1.kafka.bootstrap.servers=localhost:9092
a1.sources.source1.kafka.topics=btcusd
a1.sources.source1.kafka.consumer.group.id=flume
a1.sources.source1.channels=channel1

a1.sources.source1.interceptors=i1
a1.sources.source1.interceptors.i1.type=timestamp

#######################
# CHANNEL
#######################
a1.channels.channel1.type=memory
a1.channels.channel1.capacity=10000
a1.channels.channel1.transactionCapacity=1000

#######################
# SINK (HDFS)
#######################
a1.sinks.sink1.type=hdfs
a1.sinks.sink1.channel=channel1
a1.sinks.sink1.hdfs.path=/btcusd/btcusd/%y-%m-%d
a1.sinks.sink1.hdfs.rollInterval=5
a1.sinks.sink1.hdfs.rollSize=1024
a1.sinks.sink1.hdfs.rollCount=10
a1.sinks.sink1.hdfs.fileType=DataStream
