a1.sources = r1
a1.channels = c1
a1.sinks = k1

# Source (your API)
a1.sources.r1.type = ApiSource
a1.sources.r1.apiUrl = https://biquote.io/api/BTCUSD

# Channel (memory)
a1.channels.c1.type = memory

# Kafka Sink (send to Kafka topic)
a1.sinks.k1.type = org.apache.flume.sink.kafka.KafkaSink
a1.sinks.k1.kafka.bootstrap.servers = localhost:9092
a1.sinks.k1.kafka.topic = btcusd
a1.sinks.k1.kafka.flumeBatchSize = 20
a1.sinks.k1.kafka.producer.acks = 1

# Bindings
a1.sources.r1.channels = c1
a1.sinks.k1.channel = c1
